# Generated by Django 5.2.6 on 2025-10-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_roomdata_room_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdata',
            name='room_hour',
            field=models.IntegerField(default=2),
        ),
    ]
