# Generated by Django 5.2.6 on 2025-09-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdata',
            name='room_available',
            field=models.BooleanField(default=True),
        ),
    ]
